# Generated by Django 2.2.5 on 2020-11-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Book_Genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.BookCategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Movie_Genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.MovieCategory'),
        ),
    ]
