# Generated by Django 2.2.5 on 2020-11-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='plot',
            field=models.TextField(null=True),
        ),
    ]
