# Generated by Django 2.2.5 on 2020-11-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('detective', 'Detective'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sf', 'SF'), ('fantasy', 'Fantasy'), ('martial_arts', 'Martial_arts'), ('romance', 'Romance'), ('other', 'Other')], default='other', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Book Category',
            },
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('detective', 'Detective'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sf', 'SF'), ('fantasy', 'Fantasy'), ('martial_arts', 'Martial_arts'), ('romance', 'Romance'), ('other', 'Other')], default='other', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Movie Category',
            },
        ),
    ]
